In [410]:
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import pandas as pd
import numpy as np
from numpy import dot
from numpy.random import normal as rnorm
from numpy import mat
import scipy.optimize as opt
from numpy import exp
from numpy import log
from scipy.sparse import diags
import time
from sys import getsizeof as siz
import random as rnd

In [411]:
df=pd.read_csv('Yogurt100N.csv')

In [416]:
choice=df.as_matrix(columns=['Brand 1','Brand 2','Brand 3','Brand 4'])  # or using df.columns[:]
price=df.as_matrix(columns=['Price 1','Price 2','Price 3','Price 4'])
feat=df.as_matrix(columns=['Feature 1','Feature 2','Feature 3','Feature 4'])
d=10  # Draws
n= price.shape[0]
h=len(set(df['Pan I.D.']))
cov_n=5 # covriance matrix dimentions
mean_n=5 # number of means
tri = np.zeros((cov_n,cov_n))
para0=[1,2,3,-40,5,6,7,8,9,10]  # for only diagnal cov matrix
nbr=4
a=np.zeros((n*d,nbr))

In [417]:
print(n,h)

2430 100


In [418]:
# For element-wise operation, we need to make the dimention the same

In [419]:
choice=np.tile(choice,(d,1))
price=np.tile(price,(d,1))
feat=np.tile(feat,(d,1))

In [420]:
print(choice.shape,price.shape,feat.shape)

(24300L, 4L) (24300L, 4L) (24300L, 4L)


## Difference draws
- Same across all households
- Same random number for the same households
- Different random numbers for each observations

### Different across all observations

In [421]:
rnd.seed(1)
mu, sigma = 0, 1
z=rnorm(mu,sigma,n*cov_n*d)
ini_draw=z.reshape((n*d,cov_n))
ini_draw.shape

(24300L, 5L)

In [422]:
def LogLike(para):
    
    cho=diags(para[5:10], 0).toarray()
    t=para[0:5]+dot(ini_draw.reshape(-1,cov_n),cho)
    a[:,0:3]=t[:,0:3]  # brand preference  #np.hstack, np.concatenate, x.extend(y)
    price_beta=t[:,3].reshape(-1,1) # coeficient for price
    feature_beta=t[:,4].reshape(-1,1) # for feature
    util=a+price_beta*price+feature_beta*feat
    prob=exp(util)/np.sum(exp(util),1).reshape(d*n,-1)
    prob2=np.sum(prob*choice,1)
    prob3=prob2.reshape(n,-1)
    prob_ave=np.average(prob3,axis=1)
    return -np.sum(log(prob_ave))

In [423]:
t0 = time.time()
fit = opt.minimize(LogLike, para0, method='BFGS', tol=1e-6)
t1 = time.time()
total = t1-t0
print('time:', total)

time: 5.26300001144


In [424]:
fit

      fun: 2225.4460649780603
 hess_inv: array([[  2.48609358e-02,   4.57827206e-03,  -7.71078914e-02,
         -6.21916808e-01,   6.54087432e-02,  -1.00721541e-04,
         -3.09390239e-03,  -2.51189510e-02,   3.81424335e-01,
          1.45636896e-02],
       [  4.57827206e-03,   4.76132297e-03,  -3.65495834e-03,
         -4.29778298e-02,   3.44840648e-03,  -2.27549711e-04,
         -1.40074322e-03,  -1.12400123e-02,   3.19007196e-02,
          4.24262244e-03],
       [ -7.71078914e-02,  -3.65495834e-03,   1.42306318e+00,
          2.56320255e+00,  -1.21257412e+00,  -3.26429654e-03,
          4.11867894e-03,  -8.02849166e-02,  -7.46559580e-01,
         -9.66546298e-02],
       [ -6.21916808e-01,  -4.29778298e-02,   2.56320255e+00,
          2.15117011e+01,  -2.18963950e+00,  -9.75006382e-03,
          6.29024477e-02,   3.76635788e-01,  -1.22695774e+01,
         -1.87917510e-01],
       [  6.54087432e-02,   3.44840648e-03,  -1.21257412e+00,
         -2.18963950e+00,   1.31984477e+00,  

In [404]:
x=np.array(range(0,10))
mat=x.reshape(2,5)

In [405]:
mat


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [406]:
mat2=np.repeat(mat,3,axis=0)
mat2

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [409]:
mat3=np.tile(mat,(3,1))
mat3

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [305]:
    
    para=para0
    cho=diags(para[5:10], 0).toarray()
    t=para[0:5]+dot(ini_draw.reshape(-1,cov_n),cho)
    a[:,0:3]=t[:,0:3]  # brand preference  #np.hstack, np.concatenate, x.extend(y)
    price_beta=t[3] # coeficient for price
    feature_beta=t[4] # for feature

In [309]:
a.shape,feat.shape,price.shape

((12150L, 4L), (12150L, 4L), (12150L, 4L))

In [314]:
price_beta.shape

(5L, 1L)

In [308]:
util=a+price_beta*price+feature_beta*feat


ValueError: operands could not be broadcast together with shapes (5,) (12150,4) 

In [317]:
-np.sum(log(prob_ave))

1.4127274576846895

In [320]:
 prob=exp(util)/np.sum(exp(util),1).reshape(d*n,-1)
prob

array([[  3.17753004e-02,   9.68134466e-01,   1.65620577e-05,
          7.36712095e-05],
       [  1.26536582e-04,   9.99847520e-01,   2.55571508e-05,
          3.85940855e-07],
       [  3.95756182e-08,   9.98943011e-01,   1.23965203e-04,
          9.32983908e-04],
       ..., 
       [  7.66487037e-01,   2.00423497e-01,   2.02699848e-04,
          3.28867665e-02],
       [  1.15335965e-07,   9.99949706e-01,   4.27566361e-05,
          7.42219460e-06],
       [  1.34737508e-07,   1.75193127e-07,   9.99999536e-01,
          1.54346825e-07]])

In [321]:
    prob2=np.sum(prob*choice,1)
prob2

array([  7.36712095e-05,   3.85940855e-07,   9.32983908e-04, ...,
         3.28867665e-02,   7.42219460e-06,   1.54346825e-07])

In [326]:
    prob_ave=np.average(prob3,axis=1)
prob_ave

array([  2.02863127e-04,   2.20235479e-01,   5.66221359e-01, ...,
         8.60451506e-03,   3.29179093e-03,   2.96187708e-02])

In [328]:
     -np.sum(log(prob_ave))

5600.6074623584045

In [325]:
prob3=prob2.reshape(n,-1)
prob3.shape

(2430L, 5L)

In [426]:
para0[0:5]

[1, 2, 3, -40, 5]